# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    user_register:
        class: AppBundle\User\Register
        arguments: [ '@logger' ]

    my.listener:
        class: AppBundle\EventListener\logEntity
        tags:
            - { name: doctrine.event_listener, event: postPersist }